# Generated by Django 5.1.4 on 2024-12-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeNoString', models.CharField(max_length=50)),
                ('employeeName', models.CharField(max_length=200)),
                ('employeeStatus', models.CharField(choices=[('g', 'Пікнувся'), ('d', 'Не пікнувся')], default='d', max_length=1)),
            ],
        ),
    ]
