# Generated by Django 5.1.4 on 2024-12-10 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_table', '0003_alter_employees_options_alter_employees_employeename_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'ordering': ['employeeTerminalNo'], 'verbose_name': 'Працівник', 'verbose_name_plural': 'Працівники'},
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='employeeNoString',
            new_name='employeeTerminalNo',
        ),
    ]
