# Generated by Django 5.1.4 on 2024-12-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_table', '0004_alter_employees_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='employeeTerminalNo',
            field=models.IntegerField(verbose_name='Номер в терміналі'),
        ),
    ]
