# Generated by Django 5.1.4 on 2024-12-13 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_table', '0005_alter_employees_employeeterminalno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='employeeName',
            field=models.CharField(max_length=200, unique=True, verbose_name="Прізвище та ім'я"),
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acs_time', models.DateTimeField(blank=True, null=True, verbose_name='Час події')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access_table.employees', verbose_name='Працівник')),
            ],
            options={
                'verbose_name': 'Запис з терміналу',
                'verbose_name_plural': 'Записи з терміналу',
                'ordering': ['acs_time'],
            },
        ),
    ]
