# Generated by Django 5.1.4 on 2024-12-13 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_table', '0006_alter_employees_employeename_records'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employees',
            new_name='Employee',
        ),
        migrations.RenameModel(
            old_name='Records',
            new_name='Record',
        ),
    ]
